Styling
NickEmma/bookstore pull request #5
Opened 2022-08-17 23:45 UTC by NickEmma

- I followed the details of the Bookstore design in [Zeplin](https://zeplin.io/).

-  I opened the project Bookstore CMS.
-  I use the information detailed in Zeplin to style the website.
- My final design should match Zeplin's design.

2022-08-18 00:07 UTC, medaminedev66 requested changes
Hi @NickEmma  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional
- The web app works as expected and runs without errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 00:07 UTC, medaminedev66 commented on src/styles/Book.css
> +}
- [ ] Following the project requirements, styling is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/).
  - [ ]  It would be preferable to include the additional sections in the book's user interface, as given by Zeplin design.
  - [ ]  Please try to stick to the fonts that were included in the Zeplin design.
- Your design:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/77190203/185263762-0f54e29b-91ce-4dc0-ab95-32c53d87e8c5.png">

- Zeplin design:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/77190203/185264010-3aedb1ed-d0c7-4794-952a-68cea1d6aae8.png">

2022-08-18 00:07 UTC, medaminedev66 commented on src/styles/AddBooks.css
> +
[OPTIONAL] To improve your UI design, it would be nicer to make the input fields, buttons, and fonts smaller:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/77190203/185264377-474f8b29-4d0f-4ac7-bfcd-b4bc75f94bd3.png">

2022-08-18 10:08 UTC, NickEmma commented on src/styles/AddBooks.css
> +
noted also and resolved. thanks @medaminedev66

2022-08-18 10:15 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @NickEmma,

✔️ Good documentation
✔️ Nice UI

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 10:19 UTC, merged

2022-10-14 11:17 UTC, NickEmma commented on src/styles/AddBooks.css
> +
@medaminedev66 Thank you for reviewing my project, I will make the necessary  corrections as suggested

2022-10-14 11:18 UTC, NickEmma commented
@TedLivist Thank you for reviewing and approving our code.